# Auto release and force cache

name: Auto release and force cache

# Controls when the action will run. Triggers the workflow only on push
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Auto release
    - name: Auto release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: ${{ github.run_id }}
        prerelease: false
        title: Latest version

    # Force cache
    - name: Force cache
      run: |
        function scan() {
            for e in `ls $1`
            do
                object=$1"/"$e
                if [ -d $object ]
                then
                    scan $object
                else
                    curl -s -o /dev/null --retry 5 "https://cdn.jsdelivr.net/gh/wuxianucw/ucw-desu@master"${object:1}
                    url="https://cdn.jsdelivr.net/gh/wuxianucw/ucw-desu@${{ github.run_id }}"${object:1}
                    code=`curl -s -o /dev/null --retry 5 -w %{http_code} $url`
                    echo "Force cache "$url" [ "$code" ]"
                    if [ $code != "200" ]
                    then
                        url="https://cdn.jsdelivr.net/gh/wuxianucw/ucw-desu@master"${object:1}
                        echo " - Try master "$url" [ `curl -s -o /dev/null --retry 5 -w %{http_code} $url` ]"
                        url="https://cdn.jsdelivr.net/gh/wuxianucw/ucw-desu@${{ github.run_id }}"${object:1}
                        echo " - Retry "$url" [ `curl -s -o /dev/null --retry 5 -w %{http_code} $url` ]"
                    fi
                    url="https://cdn.jsdelivr.net/gh/wuxianucw/ucw-desu"${object:1}
                    echo " -> "$url" [ `curl -s -o /dev/null --retry 5 -w %{http_code} $url` ]"
                fi
            done
        }
        scan .
